require 'test-helper'
require '2025/day-07-laboratories'

class TestLaboratories < Minitest::Test
  def setup
    @input = <<END
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
END
    @subject = Laboratories.parse(@input)
  end

  def test_num_beam_splits
    assert_equal 21, @subject.num_beam_splits
  end

  def test_num_tachyon_beam_splits
    assert_equal 40, @subject.num_timelines
  end
end
